### ISSUE TITLE
Allow filtering matches based on skill bracket

### ISSUE THREAD

**Issue by eblis** [odota/yasp#1192]
When viewing player matches it would be nice if we could filter the matches based on skill bracket (normal, high, very high).

The data seems to be there as I can sort based on skill bracket, it's just that I can't filter based on it (although older matches don't seem to have the skill bracket data filled in).

**Comment by howardchung** [comment]
Yes, this is possible, but requires some changes.

The current implementation is to fill in the skill data (from Postgres) for the last 20 matches only.  This is because the data isn't currently stored in the Cassandra table (player_caches) that the player pages read (and filling it in for thousands of matches would be slow).

The solution is to modify the skill.js service to write the skill data to the player_caches table.
