### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Shamshiel** [odota/yasp#859]
I really would like a Web API so it would be easier to get to the data from yasp. 

An example for a cool Web API method would be the "wordcloud". Call the method with the player_id and get the worldcloud as a result back.

Right now I have to gather it manually by loading the wordcloud javascript of the player and parse the data. Sadly it is a lot of work and error-prone.

**Comment by jgrayson676** [comment]
You can get some data as JSON by adding by adding `?json=1` to the end of a player or match url.

https://yasp.co/matches/2114545903?json=1

**Comment by howardchung** [comment]
Yes, although the JSON endpoint is mainly for us to debug and not officially supported.

The reason we haven't made an official API is that APIs tend to get hit hard with traffic.  This might increase our server costs significantly, and since most people don't care about APIs donations are only to scale with the traffic increase.

Since this is something I think would be nice to do I'll keep it open, but we need a way to make sure it doesn't increase the bills too much.

**Comment by Shamshiel** [comment]
Thank you for the quick answer.
I need the data to do real time analysis, so I will probably stick to my current method. (even if I don't like it that much)

**Comment by howardchung** [comment]
A somewhat related topic:

I quite enjoyed this post a while ago about controlling "naughty" users:
https://medium.com/@yaypie/the-naughtiness-score-9a61872c61cd#.8ic638w5r

**Comment by howardchung** [comment]
I suppose with the React SPA I will need to create one anyway.  However for now it'll probably remain undocumented and developers who want to use it can ask for guidance directly.

**Comment by howardchung** [comment]
Should be deployed.  I assume /api/matches/:match_id and api/players/:account_id will be most useful.  Please don't abuse it (it's not really designed for heavy traffic).  Try to keep it to 1 req/sec.

IDK if we should do CORS header.  @albertcui ?

**Comment by howardchung** [comment]
Reopening.  I'd like to eventually get to a point where we can publish this (an API section on the main navbar).

We are still working out what endpoints we should expose.  At the moment, it maps directly to current pages, but this means that something like the player pages send more data than required (profile, mmr, etc. on all tabs).

**Comment by zyberspace** [comment]
Hey, if you have concerns about the usage of the api, you could maybe rate limit the public api (something like 60 requests per minute) and allow third-party apps to surpass the limit by providing an additional api key.

You could then charge a monthly fee for different api usage tiers so that the additional server costs would be covered.  
Other possibilities would be to tie the rate limit to the cheeses brought or make the fee a per-request thing.

**Comment by howardchung** [comment]
I don't think Valve would approve of charging for API usage.  We'd basically be reselling their data.

**Comment by zyberspace** [comment]
Why would anyone pay for data that he can also get for free through the normal steam web api?

Maybe you could advertise it with "If you don't need the stats and analysis created by yasp, please consider using Valves steam web api for your project instead, it's free!". But i understand your concerns.

**Comment by howardchung** [comment]
I'm actually not sure who owns the data generated from replay files.  Valve wrote the code that generated them, but individual players are the ones who made the actions that generated them.
